### PR TITLE
Feature Webpack/Remove ember-browserify

### PR DESCRIPTION
**Pull request by n1ru4l**
This PR implements a WebpackDependencyPlugin that bundles the required npm dependencies and also creates shim for those.

I think https://github.com/oskarrough/ember-date-fns/pull/9 is not an option since it introduces bower dependencies and furthermore imports the whole date-fns library although only two functions are required.

Full list of changes:
- Update dependencies
- Move bower dependencies to npm dependencies
- Replace jshint with eslint
- Adds indent eslint rule to unify indent to 2 spaces across all files
- Adds WebpackDependencyPlugin to bundle and generate the required npm packages

### CODE REVIEW

**Comment by oskarrough** [comment]
Thank you very much for this — and thank you @knownasilya for #9.

Personally I'd also prefer not to use bower. What I like about ember-browserify is that you don't have to do anything but import what you want. There's no extra API to learn. I really wish ember-cli would solve this. Anyway ;)

As I have zero webpack experience I worry that I won't be able to maintain this but I would like to merge and get on with it. @n1ru4l (or anyone listening) are you interested in permissions to the repo?

**Comment by oskarrough** [comment]
Another question, if you install ember-date-fns in your ember project and want to import another date-fns method, would it be possible?

With browserify you could easiliy import any date-fns helper in the consuming app as well.

**Comment by n1ru4l** [comment]
@oskarrough I would also like ember-cli handling imports and requires. That one of the most annoying parts I miss from toolings like webpack and formerly browserify. I hope that becomes a core functionality in the future.

It is not possible to import other date-fns methods other than the ones defined over here: https://github.com/oskarrough/ember-date-fns/pull/10/files#diff-168726dbe96b3ce427e7fedce31bb0bcR15

This brings the benefit of only having the minimum required code of date-fns inside the build.
Consumers of the addon can import them like the following:
```javascript
import format from 'date-fns/format'
import distanceInWordsToNow from 'date-fns/distance_in_words_to_now'
```

I could make this part configurable, so that users could list additional functions inside their `ember-cli-build.js`.

Edit: Also I could help out with maintaining this projects, since I am going to use it in a project.

**Comment by knownasilya** [comment]
Would love to see this merged.

**Comment by n1ru4l** [comment]
I will try to merge this today :)

**Comment by n1ru4l** [comment]
@oskarrough I pushed some more changes, the feature is now ready for getting merged. How do you want to handle publishing to npm? Will you grant me publishing permissions or do you want to publish the package yourself after I merged this PR?

**Comment by oskarrough** [comment]
@n1ru4l you should have permission to publish on NPM now. Merge and publish at will! I'm very glad that you're helping out.

**Pull request merged**
